### ISSUE TITLE
META

### ISSUE THREAD

**Issue by devfoo-one** [robme91/se-nbno-docu#8]
- [x] Titel: "Dokumentation zum Semesterprojekt Software-Engineering: NBNO (no beer is ooch no option)"
- [x] Authorenangabe: Software-Engineering entfernen
- [x] Datum entfernen (1. Kapitel)
- [x] Literatur entfernen, Fußnoten reichen
- [x] letterpaper a4 (Siehe IEEEtran_HOWTO.pdf : 3)
- [x] Listings Schriftgröße kleiner

**Comment by devfoo-one** [comment]
Generelles

- Erste Erwähnung von Fremdwörtern / Eigennamen ... Kursiv
- Code in `\texttt{}`
- keine `\newline`

**Comment by devfoo-one** [comment]
closes #4

**Comment by devfoo-one** [comment]
closes #2
